[book]
authors = ["Gerred Dillon"]
language = "en"
multilingual = false
src = "src"
title = "Building an Agentic System"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/gerred/building-an-agentic-system"
git-repository-icon = "fa-github"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
additional-css = ["custom.css"]

[preprocessor.mermaid]
command = "mdbook-mermaid"
