[book]
authors = ["Gerred Dillon"]
language = "en"
multilingual = false
src = "src"
title = "The Agentic Systems Series"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/gerred/building-an-agentic-system"
git-repository-icon = "fa-github"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
additional-css = ["custom.css"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.linkcheck]
# Check for broken links in the book
follow-web-links = false
exclude = ["^https://github.com/.*/pull/.*", "^https://github.com/.*/issues/.*"]
# Enable more thorough checking
warning-policy = "error"
